'use strict'

const crypto = require('crypto')

const ENC_KEY = 'bf3c199c2470cb477d907b1e0917c17b'

const IV = '5183666c72eec9e4'

// ENC_KEY and IV can be generated by crypto.randomBytes(32).toString('hex')

const encrypt = (val) => {
  const cipher = crypto.createCipheriv('aes-256-cbc', ENC_KEY, IV)
  let encrypted = cipher.update(val, 'utf8', 'base64')
  encrypted += cipher.final('base64')

  return encrypted
}

const decrypt = (encrypted) => {
  const decipher = crypto.createDecipheriv('aes-256-cbc', ENC_KEY, IV)
  const decrypted = decipher.update(encrypted, 'base64', 'utf8')
  return (decrypted + decipher.final('utf8'))
}

export const PasswordHelpers = { encrypt, decrypt }
